//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionDispositivos.Backend.Business.Bussiness.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class devicesEntities : DbContext
    {
        public devicesEntities()
            : base("name=devicesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gateway> gateway { get; set; }
        public virtual DbSet<light_meter> light_meter { get; set; }
        public virtual DbSet<water_meter> water_meter { get; set; }
    }
}
